model_path: r'C:\Users\manue\Documents\ASLFeat\model.ckpt-0'
img_path: r'C:\Users\manue\Documents\ASLFeat\imgs\test_img1.jpg'
net:
  max_dim: 2048
  config:
    kpt_n: 100
    kpt_refinement: true
    deform_desc: 1
    score_thld: 0.5
    edge_thld: 10
    multi_scale: true
    multi_level: true
    nms_size: 3
    eof_mask: 5
    need_norm: true
    use_peakiness: true
match:
  ratio_test: 0.8
  cross_check: true